### ISSUE TITLE
Move devices to "devicetypes" folder

### ISSUE THREAD

**Issue by disforw** [fortrezz/smartthings#1]
In order for people to properly import your (awesome) device handlers in to the SmartThings IDE you need to move them in to a folder in github called "devicetypes". Doing this will allow people to easily add your repo and pull your code from there. Another benefit is in case you make a change, the change will be highlighted so people know to update.

**Comment by dantheman2865** [comment]
This is a great idea. This repo is designed for human interaction, though. Maybe I'll create a separate repo which is the same files, but organized for automatic import into ST IDE. Would you be willing to link me to the instructions for adding our repo to the IDE? That would be valuable to put in the README of the new repo.

**Comment by disforw** [comment]
Have you linked your Github account with your IDE account yet?
In IDE goto the device handlers tab and click the settings button on the right,  they are you will be able to link your accounts together.

**Comment by disforw** [comment]
Once that is done, click add new repo at the bottom. Use your current repo information of owner=fortrezz and name=smartthings and branch=master

Now You will be able to use the COMMIT CHANGES button to upload your code directly to GitHub

**Comment by disforw** [comment]
http://docs.smartthings.com/en/latest/tools-and-ide/github-integration.html
For more info

**Comment by venturanc** [comment]
Is there still any plan to update the folder structure to be compatible with SmartThings GitHub integration?

**Comment by dantheman2865** [comment]
Hello, because the SmartThings platform is in such disarray we are waiting to see how things develop before we change up the structure. We have made some updates to DTHs to address minor issues, but FortrezZ (with whom I contract) is not investing a lot of effort into the SmartThings Classic platform.

**Comment by Levahj** [comment]
Hi Dan,

I am trying to get my Fortrezz MIMO2+ DTH's moved over from the Classic App to the new Connect App.   I assume you meant in your message a year + ago here that FortrezZ is not investing a lot of effort into the new  SmartThings Connect App?  Anyways, I have a very important use case for my MIMO2+ and the DTH code you made updates to works on the new Connect App but only one of the two relays and contacts shows in the App but not the second one. 
It is important enough to me that I would like to hire you for your services to tweak the DTH to get what I need out of it.  It is 80% there but I am not a programmer so dont know how to get the final 20% done.   Can you reach out to me and we can talk about it you consulting for me on this?
Marc Levaggi
marc.levaggi@gmail.com
408-656-3034

Thank you!

**Comment by dantheman2865** [comment]
Hi Marc, I'll chat with you directly. I'm not actively developing for SmartThings so it might not make sense for you and I to work together. I am also closing this issue for the same reason.
