### ISSUE TITLE
FMI device handler throws “java.net.SocketTimeoutException: Read timed out” error.

### ISSUE THREAD

**Issue by constjs** [fortrezz/smartthings#3]
The DTH throws a “java.net.SocketTimeoutException: Read timed out” error.  The chart still gets created, and you can see the URL in Live Logging, but it times out.  The limit ST has is 10 seconds, but http://iot.swiftlet.technology/fortrezz/chart.php is taking anywhere between 12-19 seconds.

**Comment by dantheman2865** [comment]
This was resolved by optimizing the chart generation code.
