### ISSUE TITLE
6 Month and Yearly Consumption Tracking

### ISSUE THREAD

**Issue by kodebearkc** [fortrezz/smartthings#6]
DanTheMan2865,
Would it be possible to add a Yearly Goal and or tracking to the SmartApp?
We have Daily, Weekly and 4 weeks but it would be ideal for me if we had a Yearly consumption goal. Or even a 6 month Consumption Goal.
The main reason i bought and installed the FortrezZ water meter was to track my usage against some water filters and Softener Cartridges i have in place. And I need to track my water use against their expected life span. Lets say that's 40,000 Gal of water. If i only have as far out as 4 weeks that makes that comparison hard. If i had the ability to track a year's worth then it would be much easier.

Would it be possible to add a 6 month and or yearly tracking to this SmartApp?

**Comment by dantheman2865** [comment]
Hello kodebearkc, I don't believe FortrezZ is planning to update this SmartApp. That being said, this would be a good use for the Water Use dashboard: https://dashboard.fortrezz.com/#!/

**Comment by kodebearkc** [comment]
I am unable to access that link. I sign up for an id and it errors no matter what I do. I’m unable to create an ID to access that water dashboard. 

 

-        Adam
