### ISSUE TITLE
smartapp.groovy for flowmeter (fmi)

### ISSUE THREAD

**Issue by domo335** [fortrezz/smartthings#8]
Where did the smartapp.groovy go for the flowmeter (fmi)?

**Comment by dantheman2865** [comment]
@domo335 Which smart app are you looking for? There are two, in separate sub-folders: https://github.com/fortrezz/smartthings/tree/master/flow%20meter%20(fmi)

**Comment by domo335** [comment]
Sorry, my issue was the fact of the water meter device being recognized as a energy meter and not a water meter. Thanks for the help
